-define(DB_HOSTNAME, "localhost").
-define(DB_USERNAME, "erlang").
-define(DB_PASSWORD, "erlang").
-define(DB_DATABASE, "blog").
-define(DB_POOL_SIZE, 50).
-define(APP_PATH, "/Users/Moski/erlang/apps/blog").